// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlyHndZfxJTuAmx8UCsOrbWm0j1pjL7Y',
    appId: '1:825976225113:web:ef92874b1d1a826b6b2048',
    messagingSenderId: '825976225113',
    projectId: 'inventif-c98ab',
    authDomain: 'inventif-c98ab.firebaseapp.com',
    storageBucket: 'inventif-c98ab.firebasestorage.app',
    measurementId: 'G-2XRMZFCYFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJg2G3AU_bzaJUv4s5m22Zhy6x94hshuY',
    appId: '1:825976225113:android:fbe1afb570245f836b2048',
    messagingSenderId: '825976225113',
    projectId: 'inventif-c98ab',
    storageBucket: 'inventif-c98ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8vsm3aRs8I8O9YQYnq7vqk24gZP-m9E',
    appId: '1:825976225113:ios:c7d91a993baf1b376b2048',
    messagingSenderId: '825976225113',
    projectId: 'inventif-c98ab',
    storageBucket: 'inventif-c98ab.firebasestorage.app',
    iosBundleId: 'com.example.inventif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw8vsm3aRs8I8O9YQYnq7vqk24gZP-m9E',
    appId: '1:825976225113:ios:c7d91a993baf1b376b2048',
    messagingSenderId: '825976225113',
    projectId: 'inventif-c98ab',
    storageBucket: 'inventif-c98ab.firebasestorage.app',
    iosBundleId: 'com.example.inventif',
  );
}
